export { default as Navbar } from './Navbar';
export { default as TestNavbar } from './TestNavbar';
export { default as LogIn } from './Login';
export { default as SignUp } from './SignUp';
export { default as Home } from './Home';
export { default as Blog } from './Blog';
export { default as Contact } from './New_Arrival';
export { default as About } from './About';
export {default as DataProvider} from './DataProvider';
export {default as ViewDetails} from './ViewDetails';
export { default as Footer} from './Footer';